#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jta
Version  : 1.1
Release  : 1
URL      : https://repo1.maven.org/maven2/javax/transaction/jta/1.1/jta-1.1-sources.jar
Source0  : https://repo1.maven.org/maven2/javax/transaction/jta/1.1/jta-1.1-sources.jar
Source1  : https://repo1.maven.org/maven2/javax/transaction/jta/1.1/jta-1.1.jar
Source2  : https://repo1.maven.org/maven2/javax/transaction/jta/1.1/jta-1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CDDL-1.0
Requires: mvn-jta-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jta package.
Group: Data

%description data
data components for the mvn-jta package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/transaction/jta/1.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/javax/transaction/jta/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/transaction/jta/1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/javax/transaction/jta/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/transaction/jta/1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/javax/transaction/jta/1.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/javax/transaction/jta/1.1/jta-1.1-sources.jar
/usr/share/java/.m2/repository/javax/transaction/jta/1.1/jta-1.1.jar
/usr/share/java/.m2/repository/javax/transaction/jta/1.1/jta-1.1.pom
